# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('student_id', models.IntegerField(unique=True)),
                ('year', models.IntegerField(default=1)),
            ],
        ),
    ]
