# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
