# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20171127_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='강의 제목')),
                ('short_discription', models.CharField(blank=True, max_length=100, null=True, verbose_name='요약 설명')),
                ('class_code', models.CharField(max_length=20, unique=True, verbose_name='학수번호')),
                ('time', models.IntegerField(verbose_name='분반')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassModel')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.StudentModel')),
            ],
        ),
    ]
