# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20171127_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='class_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.ClassModel'),
        ),
    ]
