# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('a', 'Attend'), ('n', 'Absance'), ('l', 'Late')], max_length=1)),
                ('register', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classes.RegisterModel')),
            ],
        ),
    ]
