# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='class_hash',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='hash'),
        ),
    ]
