# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_registermodel_class_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='class_room',
            field=models.CharField(default='000000', max_length=10),
        ),
    ]
