# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:28
from __future__ import unicode_literals

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_registermodel_class_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='lnglat',
            field=models.CharField(blank=True, help_text='경도/위도 포맷으로 입력', max_length=50, validators=[classes.models.lnglat_validator]),
        ),
    ]
