# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(verbose_name='오늘 날짜')),
                ('attend_time', models.TimeField(verbose_name='출책 시간')),
                ('status', models.CharField(choices=[('a', 'Attend'), ('n', 'Absance'), ('l', 'Late')], max_length=1)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.RegisterModel', verbose_name='과목')),
                ('student', models.ManyToManyField(to='student.StudentModel')),
            ],
        ),
    ]
