# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_datemodel_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datemodel',
            old_name='attend_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='datemodel',
            name='status',
        ),
    ]
